name: ta
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_webservice: 0.0.20-nullsafety.5
  google_place: ^0.4.7

  flutter_animate: ^4.5.2
  http: ^0.13.6
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  permission_handler: ^12.0.0+1
  flutter_reactive_ble: ^5.4.0
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/navigate.png # Pastikan file logo ada di folder assets
    - assets/navigatedua.png
  fonts:
    - family: Aileron
      fonts:
        - asset: assets/fonts/aileron/Aileron-Regular.otf
        - asset: assets/fonts/aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/aileron/Aileron-Italic.otf
          style: italic
        - asset: assets/fonts/aileron/Aileron-BoldItalic.otf
          weight: 700
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

    - family: DMSans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/dm-sans/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm-sans/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dm-sans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
