// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvENGKuX3rk1koDsRoNOPfOe1ldM1ULaA',
    appId: '1:477001738591:web:e4f898932dd9b6cb88eeea',
    messagingSenderId: '477001738591',
    projectId: 'beaming-talent-457712-p3',
    authDomain: 'beaming-talent-457712-p3.firebaseapp.com',
    storageBucket: 'beaming-talent-457712-p3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqN1yEG6MdHoIoXF9dglYzyGGOHnhEU4',
    appId: '1:477001738591:android:617f2b963c08332f88eeea',
    messagingSenderId: '477001738591',
    projectId: 'beaming-talent-457712-p3',
    storageBucket: 'beaming-talent-457712-p3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1nCwBKvsPGBEQ-BTu1t0q971g1ktRjU',
    appId: '1:477001738591:ios:7d6e2f2c0fcd35ee88eeea',
    messagingSenderId: '477001738591',
    projectId: 'beaming-talent-457712-p3',
    storageBucket: 'beaming-talent-457712-p3.firebasestorage.app',
    iosBundleId: 'com.example.davita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1nCwBKvsPGBEQ-BTu1t0q971g1ktRjU',
    appId: '1:477001738591:ios:7d6e2f2c0fcd35ee88eeea',
    messagingSenderId: '477001738591',
    projectId: 'beaming-talent-457712-p3',
    storageBucket: 'beaming-talent-457712-p3.firebasestorage.app',
    iosBundleId: 'com.example.davita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvENGKuX3rk1koDsRoNOPfOe1ldM1ULaA',
    appId: '1:477001738591:web:eaf666fca63efc7288eeea',
    messagingSenderId: '477001738591',
    projectId: 'beaming-talent-457712-p3',
    authDomain: 'beaming-talent-457712-p3.firebaseapp.com',
    storageBucket: 'beaming-talent-457712-p3.firebasestorage.app',
  );
}
